from dotenv import load_dotenv
from emulation_config import *
import os
import sys
from typing import Any, Optional, Type, Literal
from node_spec.structure_schema import *
from langchain_openai import AzureChatOpenAI

load_dotenv()


def _is_max_context_length_error(exc: Exception) -> bool:
    message = str(exc).lower()
    return (
        "maximum context length" in message
        and (
            "error code: 400" in message
            or "invalid_request_error" in message
            or "invalid 'input'" in message
        )
    )

def create_tool_prompt(
    name: str,
    desc: str,
    tool_args: Any,
    exp_out: Any,
    exp_in: Any,
    tool_example_pairs: Optional[list[tuple[Any, Any]]] = None,
) -> str:
    """
    Build the LLM prompt for emulating a tool response.

    Args:
        name (str): Tool name.
        desc (str): Tool description.
        tool_args (Any): Runtime tool invocation arguments.
        exp_out (Any): Expected output schema or description.
        exp_in (Any): Expected input schema or description.
        tool_example_pairs (Optional[list[tuple[Any, Any]]]): Optional examples of input/output pairs.

    Return:
        str: Fully constructed tool emulation prompt.
    """
    prompt = (
        "You are simulating a tool invocation generated by an LLM-based agent.\n\n"
        "Your task is to generate a short, realistic tool response that strictly "
        "corresponds to the tool’s contract and the specific invocation provided.\n\n"

        f"Tool name:\n{name}\n\n"

        f"Tool description:\n{desc}\n\n"

        "Tool expected input arguments (schema / specification):\n"
        f"{exp_in}\n\n"

        "Tool invocation arguments (actual values passed by the agent):\n"
        f"{tool_args}\n\n"

        "Tool expected output (schema / description):\n"
        f"{exp_out}\n\n"
    )

    if tool_example_pairs:
        prompt += (
            "Below are example tool invocations and their corresponding outputs. "
            "Use them only as guidance for structure, tone, and level of detail.\n\n"
        )
        for i, (example_input, example_output) in enumerate(tool_example_pairs, 1):
            prompt += (
                f"Example {i}:\n"
                f"Invocation arguments:\n{example_input}\n"
                f"Tool response:\n{example_output}\n\n"
            )

    prompt += (
        "Now generate the tool response for the given invocation.\n\n"
        "Requirements:\n"
        "- Use only the provided invocation arguments; do not invent missing inputs.\n"
        "- Respect optional vs required arguments as defined in the input schema.\n"
        "- Ensure the response conforms to the expected output description.\n"
        "- Be concise, realistic, and deterministic.\n"
        "- Do not include explanations, metadata, or formatting outside the response.\n"
        "- Output formatting rule:\n"
        "  - If the expected output is a single value (e.g., list/number/string), return that value AS-IS.\n"
        "  - Only return a JSON object/dict when the expected output schema explicitly specifies multiple fields.\n"
        "- Return ONLY the tool response.\n"
    )

    return prompt

tool_emulate_llm = AzureChatOpenAI(
                deployment_name=os.getenv("AZURE_DEPLOYMENT_NAME_EMULATION"),
                model=os.getenv("AZURE_MODEL_NAME_EMULATION"),
                api_version=os.getenv("AZURE_API_VERSION_EMULATION"),
                azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT_EMULATION"),
                api_key=os.getenv("AZURE_API_KEY_EMULATION"),
                temperature=0)

def llm_emulate_response(
    name: str,
    desc: str,
    tool_args: Any,
    exp_out: Any,
    exp_in: Any,
    tool_example_pairs: Optional[list[tuple[Any, Any]]] = None,
) -> str:
    """
    Invoke the emulation LLM and return its generated content.

    Args:
        name (str): Tool name.
        desc (str): Tool description.
        tool_args (Any): Runtime tool invocation arguments.
        exp_out (Any): Expected output schema or description.
        exp_in (Any): Expected input schema or description.
        tool_example_pairs (Optional[list[tuple[Any, Any]]]): Optional examples of input/output pairs.

    Return:
        str: Emulated tool response content.
    """
    effective_example_pairs = list(tool_example_pairs or [])

    while True:
        prompt = create_tool_prompt(
            name=name,
            desc=desc,
            tool_args=tool_args,
            exp_out=exp_out,
            exp_in=exp_in,
            tool_example_pairs=effective_example_pairs or None,
        )
        try:
            print(f"[EMULATION TOOL CALL] {name} args={tool_args}", file=sys.stderr, flush=True)
            resp = tool_emulate_llm.invoke(prompt)
            content = getattr(resp, "content", "") or ""
            print(f"[EMULATION TOOL RESPONE] {content}")
            return content
        except Exception as exc:
            if not _is_max_context_length_error(exc):
                raise

            if not effective_example_pairs:
                raise ValueError(
                    "Tool emulation prompt still exceeds the model context window "
                    "after removing all tool_example_pairs."
                ) from exc

            effective_example_pairs.pop()
